# Generated by Django 4.2.7 on 2023-12-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('HUMOR', 'Humor'), ('ACAO', 'Ação'), ('CIENCIA', 'Ciência'), ('HORROR', 'Horror'), ('FANTASIA', 'Fantasia'), ('OUTROS', 'Outros')], max_length=20),
        ),
    ]
